# Generated by Django 2.2.6 on 2019-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentarios', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'denuncias',
            },
        ),
        migrations.CreateModel(
            name='Elogios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentarios', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'elogios',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rua', models.CharField(max_length=45)),
                ('cep', models.IntegerField()),
                ('bairro', models.CharField(max_length=45)),
                ('cpf', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'funcionario',
            },
        ),
        migrations.CreateModel(
            name='FuncionarioTelefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'funcionario_telefone',
            },
        ),
        migrations.CreateModel(
            name='Ouvidoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ouvidoria',
            },
        ),
        migrations.CreateModel(
            name='Reclamacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentarios', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'reclamacoes',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'relatorio',
            },
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('comentarios', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'sugestoes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
